version: "4.24"

services:
  econetbackendtest_app:
    container_name: EconetBackendTest_app
    image: zibusisoncube-EconetBackendTest_live_app:1.0.0
    build: .
    ports:
      - "4001:4001"
    environment:
      - DB_URL=postgresql://admin:admin@econetbackendtest_db:5432/econetdb
    depends_on:
      - econetbackendtest_db
  econetbackendtest_db:
    container_name: econetbackendtest_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=econetdb
    volumes:
      - econetdata:/var/lib/postgresql/database 
volumes:
  econetdata: {}   